# Generated by Django 5.2.11 on 2026-02-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qtde', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
