# Generated by Django 4.2.29 on 2026-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_venda_perfil_itemvenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('C', 'CONCLUIDA'), ('X', 'CANCELADA')], default='P', max_length=1),
        ),
    ]
